Matías Alloatti - 2020
This notebook was done compiling tutorials from:
1. https://pytorch.org/tutorials/
2. https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

# What is PyTorch?

## It’s a Python-based scientific computing package targeted at two sets of audiences:

    A replacement for NumPy to use the power of GPUs
    a deep learning research platform that provides maximum flexibility and speed
    
#### The torch package contains data structures for multi-dimensional tensors and mathematical operations. Additionally, it provides many utilities for efficient serializing of Tensors, arbitrary types, and other useful utilities. 
#### It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU.

In [2]:
# base library:
import torch

In [3]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)
# values in the allocated memory will appear as the initial values when an uninitialized matrix is created.

tensor([[1.7088e-04, 1.4586e-19, 4.0556e-08],
        [2.5892e-12, 4.0285e-11, 2.6706e-06],
        [1.1704e-19, 1.3563e-19, 1.3563e-19],
        [4.5071e+16, 1.6612e-04, 2.6179e-12],
        [4.0058e-11, 4.2187e-08, 5.8253e-10]])


In [4]:
# Construct a randomly initialized Tensor:
# note: to increase the reproducibility of result, we often set the random seed to a specific value first
torch.manual_seed(1)
x = torch.rand(5, 3)            # Initialize with random numbers (uniform distribution)
print('random numbers (uniform distribution):\n', x)
y = torch.randn(2, 5)           # Initialize with random numbers (normal distribution (SD=1, mean=0))
print('\nrandom numbers (normal distribution):\n',  y)
z = torch.randperm(4)           # Size 4. Random permutation of integers from 0 to 3
print('\nrandom permutations (integers from 0 to 3):\n', z)

random numbers (uniform distribution):
 tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635]])

random numbers (normal distribution):
 tensor([[-1.8349, -2.2149,  0.0436,  1.3240, -0.1005],
        [ 0.6443,  0.5244,  1.0157,  0.2571, -0.9013]])

random permutations (integers from 0 to 3):
 tensor([1, 3, 2, 0])


In [5]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x,x.type())
# Type can also be specified by .type()
x = x.type(torch.float)
print('\n',x,x.type())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) torch.LongTensor

 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.FloatTensor


In [6]:
# Identity matrices, tensors filled with zeros or ones
eye = torch.eye(3)               # create an identity 3x3 Tensor
print('identity:\n', eye)
x1 = torch.ones(10)              # a Tensor of size 10 containing all ones
print('\nones size 10:\n',x1)
x2 = torch.ones(2, 2, 2, 2)         # a Tensor with size 2x2x2
print('\nones size 2x2x2x2:\n',x2)
x3 = torch.ones_like(eye)        # a Tensor with same shape as eye filled with ones
print('\nones with size of first matrix:\n',x3)
y = torch.zeros(10)              # a Tensor of size 10 containing all zeros
print('\nzeros size 10:\n',y)

identity:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

ones size 10:
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

ones size 2x2x2x2:
 tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

ones with size of first matrix:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

zeros size 10:
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [28]:
# a 3x3 Tensor with rows: [1,1,1],[2,2,2] and [3,3,3] using .fill_() function
x = torch.ones(3, 3) # 1  1  1
x[1].fill_(2)        # 2  2  2
x[2].fill_(3)        # 3  3  3
print('',x)

# initialize Tensor with a range of value
y1 = torch.arange(5)             # similar to range(5) but creating a Tensor
print('\nRange Tensors:\n',y1)
y2 = torch.arange(0, 5, step=1)  # size 5. Similar to range(0, 5, 1)
print('\n',y2)
# a 3x3 Tensor with 0-8 values:
z = torch.arange(9)
z = z.view(3, 3)
print('\n',z)

 tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

Range Tensors:
 tensor([0, 1, 2, 3, 4])

 tensor([0, 1, 2, 3, 4])

 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
# Construct a tensor directly from data:
x = torch.tensor([[5.5, 3],[4,5],[6,7]], dtype=torch.long)
y1 = torch.Tensor(2,3)                      # an un-initialized torch.FloatTensor of size 2x3
y2 = torch.Tensor([[1,2],[4,5]])            # a Tensor initialized with a specific array
z = torch.LongTensor([1,2,3])               # a Tensor of type Long

print('x:\n',x, x.type())
print('\ny1:\n',y1, y1.type())
print('\ny2:\n',y2, y2.type())
print('\nz:\n',z, z.type())

# Tensors are FloatTensors by default

In [8]:
# Create a tensor based on an existing tensor. 
# These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
y = x.new_zeros(5, 3, dtype=torch.float16)    # new_* methods take in sizes
print('x: ',x,'\n\ny: ',y,'\n')

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

x:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 

y:  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16) 

tensor([[-0.5404, -2.2102,  2.1130],
        [-0.0040,  1.3800, -1.3505],
        [ 0.3455,  0.5046,  1.8213],
        [-0.1814, -0.9515,  0.4057],
        [-1.5164,  0.7322,  2.2820]])


In [9]:
# linear and log scale Tensors
x = torch.linspace(1, 10, steps=10)            # a Tensor with 10 linear points for (1, 10) inclusively
print('',x)
y = torch.logspace(start=-10, end=10, steps=5) # a Tensor with 5 points: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10
print('\n',y)                                  #note that start and end points indicate exponents and not numbers

 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

 tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [10]:
# get its size:
print('size:     ', x.size())              # torch.Size is a tuple
# get its number of total elements
print('elements: ', torch.numel(x))    
# get its type:
print('type:     ', x.type())

size:      torch.Size([10])
elements:  10
type:      torch.FloatTensor


Tensor types:

| Data type | dtype | CPU tensor | GPU tensor |
|------|------|------|------|
| 32-bit floating point | torch.float32 or torch.float | torch.FloatTensor | torch.cuda.FloatTensor |
| 64-bit floating point | torch.float64 or torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor |
| 16-bit floating point | torch.float16 or torch.half | torch.HalfTensor | torch.cuda.HalfTensor |
| 8-bit integer (unsigned) | torch.uint8 | torch.ByteTensor | torch.cuda.ByteTensor |
| 8-bit integer (signed) | torch.int8 | torch.CharTensor | torch.cuda.CharTensor |
| 16-bit integer (signed) | torch.int16 or torch.short | torch.ShortTensor | torch.cuda.ShortTensor |
| 32-bit integer (signed) | torch.int32 or torch.int | torch.IntTensor | torch.cuda.IntTensor |
| 64-bit integer (signed) | torch.int64 or torch.long | torch.LongTensor | torch.cuda.LongTensor |
| Boolean | torch.bool | torch.BoolTensor | torch.cuda.BoolTensor |

## Operations!

### Addition:

In [11]:
y = torch.rand(5, 3)
x = torch.ones(5,3)
# print('x:', x)
# rint('y:', y)

# Syntax 1:
print('Syn 1:', x + y, '\n')

# Syntax 2:
print('Syn 2:', torch.add(x, y), '\n')

# Syntax 3 (providing an output tensor as argument):
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print('Syn 3:', result, '\n')

# Syntax 4 (adds x to y):
y.add_(x)
print('Syn 4:', y, '\n')
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x

Syn 1: tensor([[1.7720, 1.3828, 1.7442],
        [1.5285, 1.6642, 1.6099],
        [1.6818, 1.7479, 1.0369],
        [1.7517, 1.1484, 1.1227],
        [1.5304, 1.4148, 1.7937]]) 

Syn 2: tensor([[1.7720, 1.3828, 1.7442],
        [1.5285, 1.6642, 1.6099],
        [1.6818, 1.7479, 1.0369],
        [1.7517, 1.1484, 1.1227],
        [1.5304, 1.4148, 1.7937]]) 

Syn 3: tensor([[1.7720, 1.3828, 1.7442],
        [1.5285, 1.6642, 1.6099],
        [1.6818, 1.7479, 1.0369],
        [1.7517, 1.1484, 1.1227],
        [1.5304, 1.4148, 1.7937]]) 

Syn 4: tensor([[1.7720, 1.3828, 1.7442],
        [1.5285, 1.6642, 1.6099],
        [1.6818, 1.7479, 1.0369],
        [1.7517, 1.1484, 1.1227],
        [1.5304, 1.4148, 1.7937]]) 



### More operations:

In [12]:
# 

## Indexing, resizing and more!

In [13]:
# You can use standard NumPy-like indexing and goes like a pineapple! ;) 
print(y[:, 1])
print(y[1,:])
# also for asignment
y[:, 0] = 0
print(y)

tensor([1.3828, 1.6642, 1.7479, 1.1484, 1.4148])
tensor([1.5285, 1.6642, 1.6099])
tensor([[0.0000, 1.3828, 1.7442],
        [0.0000, 1.6642, 1.6099],
        [0.0000, 1.7479, 1.0369],
        [0.0000, 1.1484, 1.1227],
        [0.0000, 1.4148, 1.7937]])


In [14]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2080])
-1.2080135345458984


In [16]:
# Concatenation and stacking of Tensors
# concatenate 3 tensors:
x = torch.Tensor([[1,2],[3,4]])
y = torch.cat((x, x, x), 0)          # Concatenate in the 0 dimension
print('concatenate (0 dimension):\n',y)
y = torch.cat((x, x, x), 1)          # Concatenate in the 1 dimension
print('concatenate (1 dimension):\n',y)
# stack 2 tensors:
z = torch.stack((x, x))
print('\nstack: ',z.size(),'\n',z)

concatenate (0 dimension):
 tensor([[1., 2.],
        [3., 4.],
        [1., 2.],
        [3., 4.],
        [1., 2.],
        [3., 4.]])
concatenate (1 dimension):
 tensor([[1., 2., 1., 2., 1., 2.],
        [3., 4., 3., 4., 3., 4.]])

stack:  torch.Size([2, 2, 2]) 
 tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])


In [29]:
# Split Tensors
x= torch.arange(9); x = x.view(3, 3);
# split in 3 chunks
y = torch.chunk(x, 3)
print('3 chunks:\n',y)
# split into chunks of at most size 2
y = torch.split(x, 2)
print('2 chunks:\n',y)

3 chunks:
 (tensor([[0, 1, 2]]), tensor([[3, 4, 5]]), tensor([[6, 7, 8]]))
2 chunks:
 (tensor([[0, 1, 2],
        [3, 4, 5]]), tensor([[6, 7, 8]]))


In [50]:
# Index select, mask select
# Index select: selects element 0 and 2 for each dimension 1.
indexes = torch.LongTensor([0, 2])      # Indexes to select
y = torch.index_select(x, 1, indexes);  # syntax: torch.index_select(input, dimension, indexes) → Tensor
print('index select:\n',y)

# Masked select: evaluates which element is >= 3
mask = x.ge(3)                             # syntax 1: Tensor=Tensor.ge(other)
torch.ge(x,3,out=mask2)                    # syntax 2: torch.ge(input, other, out=None) → Tensor
# computes input≥other element-wise. Other can be number or Tensor. out is an optional Tensor
# returns a torch.BoolTensor with True at each location where comparison is true.
print('\nmask:\n', mask)
print('\nmask2:\n',mask2)
z = torch.masked_select(x, mask); print('\nmasked select:',z)

index select:
 tensor([[0, 2],
        [3, 5],
        [6, 8]])

mask:
 tensor([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])

mask2:
 tensor([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])

masked select: tensor([3, 4, 5, 6, 7, 8])


In [55]:
# Squeeze (basically substracting a dimension)
x = torch.ones(2,1,2,1); print('x:\n',x)                        # Size 2x1x2x1
y1 = torch.squeeze(x); print('\nsqueezed:\n',y1)                # Size 2x2
y2 = torch.squeeze(x, 1);print('\nsqueezed with dim 1:\n',y2)   # Squeeze dimension 1: Size 2x2x1

# Un-squeeze a dimension (basically adding a dimension)
x = torch.Tensor([1, 2, 3]); print('\nx:\n',x)                      # Size: 3
z1 = torch.unsqueeze(x, 0); print('\nunsqueezed (dim0):\n',z1)      # Size: 1x3
z2 = torch.unsqueeze(x, 1); print('\nunsqueezed (dim1):\n',z2)      # Size: 3x1

x:
 tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])

squeezed:
 tensor([[1., 1.],
        [1., 1.]])

squeezed with dim 1:
 tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

x:
 tensor([1., 2., 3.])

unsqueezed (dim0):
 tensor([[1., 2., 3.]])

unsqueezed (dim1):
 tensor([[1.],
        [2.],
        [3.]])


In [168]:
x.copy_(y), x.t_()

RuntimeError: The size of tensor a (10) must match the size of tensor b (5) at non-singleton dimension 0

In [49]:
print(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

### Converting a Torch Tensor to a NumPy array and vice versa is a breeze. 
#### The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [27]:
# Converting Torch Tensor to NumPy ndrray:
a = torch.ones(5)
b = a.numpy()
print('type of a: ',type(a),'  ',a)
print('type of b: ',type(b),'    ',b)

# When we change the Tensor, the ndarray also changes:
a.add_(1)
print('\nTorch Tensor: ',a)
print('NumPy ndarray: ',b)

type of a:  <class 'torch.Tensor'>    tensor([1., 1., 1., 1., 1.])
type of b:  <class 'numpy.ndarray'>      [1. 1. 1. 1. 1.]

Torch Tensor:  tensor([2., 2., 2., 2., 2.])
NumPy ndarray:  [2. 2. 2. 2. 2.]


In [33]:
# Converting NumPy ndrray to Torch Tensor:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print('type of a: ',type(a),'  ',a)
print('type of b: ',type(b),'    ',b)

# When we change the ndarray, the Tensor also changes:
np.add(a, 1, out=a)
print('\nTorch Tensor: ',a)
print('NumPy ndarray: ',b)

# All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

type of a:  <class 'numpy.ndarray'>    [1. 1. 1. 1. 1.]
type of b:  <class 'torch.Tensor'>      tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

Torch Tensor:  [2. 2. 2. 2. 2.]
NumPy ndarray:  tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

In [34]:
# Tensors can be moved onto any device using the .to method.

# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!